---
name: PairDrop
version: '0.1-alpha'
slug: pairdrop
description: PairDrop is a AirDrop-like progressive web app that transfers files between
  browsers (or in this case Home Assistant clients). Data is transfered between machines
  on the same IP subnet / LAN network using WebRTC with traffic being encrypted in transit.
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
startup: application
boot: auto
options: {}
schema: {}
url: https://snapdrop.net/
panel_icon: mdi:broadcast
ingress: true
ingress_port: 3000
